# DO NOT USE THIS FILE. ONLY INCLUDING IT FOR THE EXAMPLE OF THE UNUSUAL FILESYSTEMS

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e6092d79-c5e1-4ebe-8fa7-3b8820fa1260";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D8EC-4338";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/backup" =
    { device = "/dev/disk/by-uuid/7e33b148-063d-405a-a9fa-10aad91b2a14";
      fsType = "ext4";
	  options = [ "rw" "noatime" "nofail" ];
      noCheck = true;
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/a21ca839-b050-48b8-a04b-e69c2da23eb0";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/53b550d4-502c-48ec-b5b1-572e421fab4d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}

