#!/run/current-system/sw/bin/bash

if [ `id -u` -ne 0 ]
then
  echo Please run this script as root or using sudo!
  exit
fi

if [[ ! "$1" ]]
then
  echo "You must indicate 'list' or 'delete'"
  echo "Example:"
  echo "    sudo ./gen list"
  echo "    sudo ./gen delete 55"
  exit
fi

booted=`cat /proc/cmdline | sed -n 's/^.*init=\(.*\)\/init.*$/\1/p'`
current=`ls -al /nix/var/nix/profiles/ | grep $booted | sed -E 's/.*system\-([0-9]+)\-.*/\1/'`
list=`ls -al /nix/var/nix/profiles/ | grep "system-" | sed -E 's/.*system\-([0-9]+)\-.*/\1/' | sort | uniq`

rm -f /tmp/gen-list.txt

declare -a arr=($list)
	#declare -a gens=()
for i in "${arr[@]}"
do
  if [[  ${i} == ${current} ]]
  then
    echo -E "  ${i} (current)" >> /tmp/gen-list.txt
  else
    echo -E "  ${i} " >> /tmp/gen-list.txt
  fi
done

if [ $1 == "list" ]
then
  echo "Generations:"
  cat /tmp/gen-list.txt
  exit
elif [ $1 == "delete" ]
then
  if [ ! "$2" ]
  then
    echo "You must indiacte which generation(s) to delete"
    echo "Example:"
    echo "    sudo ./gen delete 33"
    exit
  else
    if [[ ! $(cat /tmp/gen-list.txt | grep -E " ${2} ") ]]
    then
      echo "Generation ${2} does not exist! Aborting"
      exit
    elif [[ $(cat /tmp/gen-list.txt | grep -E " ${2} " | grep "current") ]]
    then
      echo "Generation ${2} is the current running generation! Aborting"
      exit
    fi
    echo "You've chosen to delete generation $2"
    read -p "Proceed? (y/N) " proceed
    if [[ "$proceed" =~ [Yy] ]]
    then
      echo "Deleting generation $2"
      rm /nix/var/nix/profiles/system-${2}-link
#      nix-env --profile /nix/var/nix/profiles/system --delete-generations "$2"
    else
      echo "Quitting"
    fi
  fi
fi

#n=1
#for arg in "$@"; do
#  echo "arg $n: $arg"
#  ((n++))
#done

