#!/run/current-system/sw/bin/bash
set -e -o pipefail

/run/current-system/sw/bin/nix flake update --flake /etc/nixos/.

sleep 1

/run/current-system/sw/bin/nixos-rebuild build --flake /etc/nixos/.

sleep 1

/run/current-system/sw/bin/nix store diff-closures /run/current-system /result > /update.txt

if [ ! -s /update.txt ]
then
  message=`echo "System is up-to-date! Nothing to do!"`
  /run/current-system/sw/bin/rm /update.txt
else
  echo "The following updates are available:"
  cat /update.txt
  echo
  read -p "Do you want to update the system now? (y/N) " proceed
  echo
  if [[ "$proceed" =~ [Yy] ]]
  then
    echo "Updating the system ..."
    /run/current-system/sw/bin/nixos-rebuild switch --flake /etc/nixos/.
  fi

  sleep .3

  /run/current-system/sw/bin/chown VAR_USERNAME:users /update.txt

  sleep .3

  /run/current-system/sw/bin/mv /update.txt /home/VAR_USERNAME/update.txt

fi

sleep .3

/run/current-system/sw/bin/rm /result

sleep .3

/run/current-system/sw/bin/nix-collect-garbage

echo
echo ${message}
echo

